scripts/build/package.sh
This PR adds a step to the build script that rewrites the import paths for date-fns functions to use the esm versions. (fixes #7)
=> Rewrite import paths in esm version to use esm version of date-fns.

src/_lib/tzTokenizeDate/index.js
=> fix : utcToZonedTime returns next day when time matches offset

src/toDate/index.js, src/toDate/test.js
This bug was quite subtle,  but it appeared when I was doing
```js
const foo = new Date('2019-04-06 23:45'
zonedTimeToUtc(foo), 'Australia/Sydney')
```
Which,  as my timezone _is_ `Australia/Sydney`,  should have returned the same date.   Instead it returned `2019-04-07 00:45`.
As this date is around DST (`2019-04-07 3:00`),  I knew that was likely a root cause.
But `tzParseTimezone` was giving the right offset when I called it manually.
I then realized that `tzParseTimezone` in `toDate` is being called with `new Date(timestamp + time)`. On investigation,  that is the local-time removed date (e.g `2019-04-06T23:45:00.000Z`).
Which is `07/04/2019, 9:45:00 am` in Australia.
That is **PAST** the DST change-over time; unlike my actual date `foo`, which is **BEFORE** the DST change-over time. …
=> fix toDate using the UTC timestamp for determining offset

src/toDate/index.js, src/toDate/test.js
Fixes #85 (at least for me).
I believe that #46 came to the wrong conclusion, or at least one that privileges the eastern hemisphere over the west. Computing and then refining the offset (as is done for the non-timezone case) seems to do a better job of matching the offset to the hour, instead of the day (or the previous/next day!).
If @dcousens or anyone else has any more times that are giving them trouble, I think the more cases we can include in the test the merrier!
=> Refine offset after initial calculation when timezone is provided

src/_lib/tzParseTimezone/index.js, src/_lib/tzParseTimezone/test.js
When porting timezones from moment I noticed some inconsistencies between those two. Further investigation led me to discover that timezones which has hyphens as delimiter instead of underscore gives 0 offset. 
You can check current behavior in [sandbox](https://codesandbox.io/s/date-fns-tz-hyphen-bug-pubr4?file=/src/index.js). 
Currently there are three (I didn't counted etc zones like `Etc/GMT-1`) [canonical timezones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List) affected: 
- "America/Port-au-Prince", 
- "America/Blanc-Sablon" 
- "Asia/Ust-Nera"
The problem was in `timezoneIANA` regex, which didn't recognized timezone names with hyphen.
=> Add support for hyphen in timezone name

src/_lib/tzParseTimezone/index.js, src/_lib/tzParseTimezone/test.js, src/getTimezoneOffset/test.js, src/toDate/index.js, src/toDate/test.js
Addresses #143 
When fixing this, a test on `toDate` using a `"UTC"` timezone string failed returning an invalid date: Turns out the timezone was being parsed as "U", which is invalid.
When looking for this I realised the parsing logic on datetime strings is wrong: it splits by ` ` and `T` (it was assuming strings were in format (`DD-MM-YYYYTHH:mm:ss`), but it also meant it split timezone names after that, such as UTC or any city which has a T in it.
So I added a test for it, and also fixed it.
Please check if every test is running, I had to disable some of them in local because some of them don't work in my timezone (I guess? on master those didn't work on my machine)
=> fix invalid timezones not returning invalid dates

src/_lib/tzParseTimezone/index.js
In our project we mock `Intl.DateTimeFormat` in order to quickly run tests against various timezones. I understand [your preferred method](https://github.com/marnusw/date-fns-tz/issues/73#issuecomment-998946188) differs, but this had been working for us up to version `1.1.4` quite nicely.
In [1.1.5](https://github.com/marnusw/date-fns-tz/releases/tag/v1.1.5) a [commit](https://github.com/marnusw/date-fns-tz/commit/3a72f7e82cfb1ff2af085c2e4963795faaf562bf) introduced `isValidTimezoneIANAString` which invokes `Intl.DateTimeFormat` **without** `new`. When mocking, this causes the error `Uncaught TypeError: Class constructor DateTimeFormatFake cannot be invoked without 'new'` which subsequently causes an `Invalid Date` error. The fix is as simple as adding `new`, which shouldn't affect anyone …
=> Add new to DateTimeFormat invocation

src/format/index.js, src/format/index.js.flow, src/fp/format/index.js.flow, src/fp/formatWithOptions/index.js.flow, src/fp/index.js.flow, src/index.js.flow, typings.d.ts
Fixes #198 
Updates the types for `format` from `date-fns` to accept `Date | Number` and removes string.
=> fix: update format types to match date-fns

src/zonedTimeToUtc/test.js
This adds 6 tests for daylight savings. It tests what is returned by zonedTimeToUtc when the zoned time argument is during the times the local clock is moved forward or backwards. 
It serves two main purposes:
1. Documenting behaviour for developers - for instance when a local time is repeated (the local clock has been turned backwards), the latter occurence is returned. This is perfectly useful behaviour, but the test serves to document it and ensure it remains consistent between updates.
2. As per the comments in the test, there is a question of what to do when a zoned time is provided which does not exist - for example when the zoned clock jumps from 01:59 to 03:00. At present the UTC time coresponding to zoned time at 01:00 is returned in the test which sets the zoned time to 02:00. …
=> testing zonedTimeToUtc daylight saving jumps

README.md, package.json
Optimise configuration for ESM exports (entry points for `cjs`: require / `esm`: import and also `typescript`: types)
**BREAKING CHANGE**: Imports from esm subpaths must be replaced by the non-esm path, since the runtime will pick the correct entry point depending on `package.json#type` property (`commonjs` vs. `module`).
Before: `import {} from 'date-fns-tz/esm/format'` -> after: `import {} form 'date-fns-tz/format'`
This superseeds the existing PR (#211 ) with additional configuration for `types` field.
---
Motivation: I was not able to use `date-fns-tz` with `esm` and `jest` without this patch being applied.
=> Optimize configuration for ESM exports (entry points for cjs / esm / typescript)

src/_lib/tzParseTimezone/index.js, src/_lib/tzParseTimezone/test.js
This PR fixes the issue that `tzParseTimezone` interprets '+00:30' as '-00:30' and vise versa.
=> Fix tzParseTimezone to parse 00:30 timezones properly

src/_lib/tzTokenizeDate/index.js
=> fix: Use `hourCycle` for browsers that support hour cycle formatting

src/_lib/tzTokenizeDate/index.js
According to my tests, format will never display unicode characters.
I ran through every single list of timezones in wikipedia (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) and not a single time did it ever produce a weird non-ascii output. In fact, putting all possible `dtf.format(date)` in a set and comparing it with:
```javascript
var s = new Set()
/* run through every timezone and do s.add(dtf.format(d)) */
s.forEach(x => console.log(x, x === x.replace(/\u200e/g, '')))
```
Produced exactly the output you would expect:
```
10/24/2023, 24:00:00 true
10/24/2023, 03:00:00 true
10/24/2023, 01:00:00 true
10/24/2023, 02:00:00 true
10/23/2023, 15:00:00 true
10/23/2023, 16:00:00 true
10/23/2023, 20:00:00 true
10/23/2023, 21:00:00 true
10/23/2023, 19:00:00 true
10/23/2023, …
```
=> tzTokenizeDate: Remove weird unneeded regex

package.json, yarn.lock
Same as https://github.com/marnusw/date-fns-tz/pull/262 but has the lockfile updated for CI to pass.
This should fix https://github.com/marnusw/date-fns-tz/issues/260 for date-fns-tz v2 which will still be an issue even [when date-fns-v3 is released](https://github.com/marnusw/date-fns-tz/pull/265).
Example where this will still be an issue after v3 is supported (real scenario from my company):
- shared-library-1 uses date-fns v2 and date-fns-tz v2 (sure they could upgrade, but haven't yet)
- shared-library-2 uses date-fns v3 but does not use date-fns-tz or shared-library-1 so they have no issue
- some-app uses shared-library-1 and shared-library-2
- date-fns-tz v2 (as a dependency of shared-library-1) will attempt to use v3 because it is available and satisfies `>=2.0.0`
- some app will …
=> Specify date-fns 2.x

package.json
This should fix the install of `date-fsn-tz` or at least throw a warn during `npm i`
=> lock `date-fns` to 2.x

docs/OptionsWithTZ.js, src/format/index.js, src/format/index.js.flow, src/format/test.js, src/formatInTimeZone/index.js, src/formatInTimeZone/index.js.flow, src/formatInTimeZone/test.js, src/fp/format/index.js.flow, src/fp/formatInTimeZone/index.js.flow, src/fp/formatInTimeZoneWithOptions/index.js.flow, src/fp/formatWithOptions/index.js.flow, src/fp/getTimezoneOffset/index.js.flow, src/fp/index.js.flow, src/fp/toDate/index.js.flow, src/fp/toDateWithOptions/index.js.flow, src/fp/utcToZonedTime/index.js.flow, src/fp/utcToZonedTimeWithOptions/index.js.flow, src/fp/zonedTimeToUtc/index.js.flow, src/fp/zonedTimeToUtcWithOptions/index.js.flow, src/getTimezoneOffset/index.js.flow, src/index.js.flow, src/toDate/index.js.flow, src/utcToZonedTime/index.js.flow, src/zonedTimeToUtc/index.js.flow, typings.d.ts
Fixes https://github.com/marnusw/date-fns-tz/issues/167
Fixes https://github.com/marnusw/date-fns-tz/issues/228
Using the original date for populating the correct replaced timezone token ensures that the DST threshold is applied to the original date, not a pre-modified date used for further formatting.
=> Improving correctness of the `formatInTimeZone` close to the DST threshold

src/format/formatters/index.ts
I think this issue emerged with TS rewrite. The second arg of `getTimeZoneOffset` should be optional.
=> fix: make getTimeZoneOffset's 2nd arg optional

src/formatInTimeZone/index.ts, src/formatInTimeZone/test.js
* fixing https://github.com/marnusw/date-fns-tz/issues/279
=> fix: formatInTimeZone incorrectly interpreting the input date string

README.md
Update links to match name change of `toZonedTime` and `fromZonedTime`
=> fix links in table of contents

src/_lib/tzTokenizeDate/index.ts
This PR fixes this [issue](https://github.com/marnusw/date-fns-tz/issues/296) by extracting `testDateFormatted` outside of `getDateTimeFormat`. This avoids re-instantiating each time `getDateTimeFormat` is called. Other details are added in the linked issue.
=> perf: extract testDateFormatted to avoid re-initialising each time getDateTiemFormat is called

src/_lib/tzIntlTimeZoneName/index.ts, src/_lib/tzIntlTimeZoneName/test.js, src/formatInTimeZone/test.js
Resolves #233
`tzIntlTimeZoneName` was the only place I found that was affected by `setDefaultOptions`
=> Compatibility with setDefaultOptions in date-fns
